"""Copy the firmware's icon outlines into the editor, as a JavaScript module.

The icon picker used to be a list of names -- "rooms_shower", "entity_valve" --
which is a poor way to choose a picture. To show them it needs the drawings, and
the drawings live in the firmware repo: `icon_svg/<group>/<name>.svg`, from which
`iconConvert.py` also generates the rasteriser's tables. This takes the same
files and writes what a browser needs.

**The manifest still decides which icons exist.** This file is only the artwork:
a name the editor is offered but has no glyph for falls back to its name, which
is exactly what the picker showed before. That is what makes it safe for the two
repos to be updated at different times -- add an icon to the firmware, and the
editor lists it the moment the manifest arrives, drawn once this is re-run.

Every one of these files is a single <path> on the same 0 -960 960 960 viewBox,
so the path data alone is enough and the module is a plain name-to-string map.
That is checked rather than assumed: a file that breaks the pattern stops this
with a message instead of being silently dropped.

    cd dashboard && python3 tools/icon-glyphs.py
    python3 tools/icon-glyphs.py --firmware ~/somewhere/else/ha_dashboard
"""

from __future__ import annotations

import argparse
import os
import re
import sys

# The sibling firmware checkout, which is where these live. Both repos are
# normally cloned beside each other; --firmware covers when they are not.
DEFAULT_FIRMWARE = os.path.expanduser(
    "~/Documents/Ich/Development/Arduino/inkplate5v2/ha_dashboard/ha_dashboard"
)

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "frontend", "src", "iconGlyphs.js")

VIEW_BOX = "0 -960 960 960"
PATH = re.compile(r"<path\b[^>]*\sd=\"([^\"]+)\"")
VIEW = re.compile(r"\sviewBox=\"([^\"]+)\"")


def read(path: str) -> str:
    """The one path in an SVG, or a reason it cannot be used."""
    svg = open(path, encoding="utf-8").read()

    view = VIEW.search(svg)
    if not view or view.group(1) != VIEW_BOX:
        raise ValueError(f"viewBox is {view.group(1) if view else 'missing'}, not {VIEW_BOX}")

    paths = PATH.findall(svg)
    if len(paths) != 1:
        raise ValueError(f"{len(paths)} <path> elements, expected exactly 1")
    return paths[0]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--firmware", default=DEFAULT_FIRMWARE)
    args = parser.parse_args()

    source = os.path.join(args.firmware, "icon_svg")
    if not os.path.isdir(source):
        print(f"No icon_svg in {args.firmware}. Pass --firmware.", file=sys.stderr)
        return 1

    glyphs: dict[str, str] = {}
    problems: list[str] = []
    for group in sorted(os.listdir(source)):
        folder = os.path.join(source, group)
        if not os.path.isdir(folder):
            continue
        for file in sorted(os.listdir(folder)):
            if not file.endswith(".svg"):
                continue
            # The same name the firmware builds: icon_path_<group>_<file>, which
            # is what the manifest offers and what a layout stores.
            name = f"{group}_{file[: -len('.svg')]}"
            try:
                glyphs[name] = read(os.path.join(folder, file))
            except ValueError as problem:
                problems.append(f"{group}/{file}: {problem}")

    if problems:
        print("These icons do not fit the pattern this generator relies on:", file=sys.stderr)
        for problem in problems:
            print(f"  {problem}", file=sys.stderr)
        return 1

    if not glyphs:
        print(f"No icons found under {source}", file=sys.stderr)
        return 1

    lines = [
        "// Generated by tools/icon-glyphs.py from the firmware's icon_svg/ -- do not",
        "// edit by hand. Re-run it when the firmware gains an icon.",
        "//",
        "// The outlines the panel draws, so the editor can show what it is offering",
        "// instead of a list of names. Which icons *exist* is the manifest's to say;",
        "// this is only the artwork, and a name with no glyph here still lists.",
        "//",
        f'// One path each, all on the same viewBox: "{VIEW_BOX}".',
        "",
        f'export const ICON_VIEW_BOX = "{VIEW_BOX}";',
        "",
        "export const ICON_GLYPHS = {",
    ]
    for name, path in sorted(glyphs.items()):
        lines.append(f'  {name}: "{path}",')
    lines.append("};")
    lines.append("")

    with open(os.path.normpath(OUT), "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))

    groups: dict[str, int] = {}
    for name in glyphs:
        groups[name.split("_", 1)[0]] = groups.get(name.split("_", 1)[0], 0) + 1
    written = os.path.normpath(OUT)
    print(f"{len(glyphs)} icons -> {written}")
    print("  " + ", ".join(f"{group} {count}" for group, count in sorted(groups.items())))
    return 0


if __name__ == "__main__":
    sys.exit(main())
